TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += rfMonitor1.db
DB += rfMonitor2.db
DB += rfMonitor3.db
DB += rfMonitor4.db
DB += rfMonitor5.db
DB += rfMonitor6.db
DB += rfMonitor7.db
DB += rfMonitor8.db


# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

